tap "anomalyco/tap"
tap "fluxcd/tap"

brew "bash-language-server"
brew "bitwarden-cli"
brew "delve"
brew "dive"
brew "fluxcd/tap/flux"
brew "golangci-lint"
brew "helmfile"
brew "k9s"
brew "kind"
brew "krew"
brew "kubelogin"
brew "kustomize"
brew "lua-language-server"
brew "anomalyco/tap/opencode"
brew "velero"
