[dev]
image=fedora:latest
pull=true
replace=false
start_now=true

additional_packages="bat ripgrep fish buildah gh curl neovim git fzf stow fd-find clang-devel make jq yq podman podman-remote ffmpeg meld poppler-utils tmux golang gopls rust cargo rust-analyzer rustfmt google-cloud-cli libxcrypt-compat.x86_64 uvx kubectl kcli restic rclone bc gettext-envsubst"

# Add third-party repositories before package installation
pre_init_hooks="printf '[google-cloud-cli]\nname=Google Cloud CLI\nbaseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=0\ngpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg\n' | sudo tee /etc/yum.repos.d/google-cloud-sdk.repo > /dev/null"
pre_init_hooks="sudo dnf install -y 'dnf5-command(copr)' && sudo dnf copr enable -y karmab/kcli"



# Export binaries to host
exported_bins="/usr/bin/go /usr/bin/gofmt /usr/bin/gopls /usr/bin/cargo /usr/bin/rustc /usr/bin/rustfmt /usr/bin/rust-analyzer /usr/bin/gcloud /usr/bin/uvx /usr/bin/kubectl /usr/bin/restic /usr/bin/rclone"

