[dev]
image=fedora:latest
pull=true
replace=false
start_now=true

additional_packages="asciinema bat bind9-next-utils btop ripgrep fish buildah gh curl neovim git fzf stow fd-find clang-devel make jq yq podman podman-remote ffmpeg meld poppler-utils tmux golang gopls rust cargo rust-analyzer rustfmt uvx kubectl restic rclone bc gettext-envsubst ruby"

# Export binaries to host
exported_bins="/usr/bin/go /usr/bin/gofmt /usr/bin/gopls /usr/bin/cargo /usr/bin/rustc /usr/bin/rustfmt /usr/bin/rust-analyzer /usr/bin/gcloud /usr/bin/uvx /usr/bin/kubectl /usr/bin/restic /usr/bin/rclone"

